
#include "TinyGLES.h"

#include <iostream>

#include <unistd.h>

int main(int argc, char *argv[])
{
// Say hello to the world!
    std::cout << "Hello world, a skeleton app generated by appbuild.\n";

// Display the constants defined by app build. \n";
    std::cout << "Application Version " << APP_VERSION << '\n';
    std::cout << "Build date and time " << APP_BUILD_DATE_TIME << '\n';
    std::cout << "Build date " << APP_BUILD_DATE << '\n';
    std::cout << "Build time " << APP_BUILD_TIME << '\n';

    tinygles::GLES theDisplay(true);

    int n = 0;
    while( theDisplay.BeginFrame() )
    {
        theDisplay.Clear(0,0,0);

        for(int n = 0 ; n < 32 ; n++ )
        {
            int w = 8 + (rand()&127);
            int h = 8 + (rand()&127);

            int x = rand()%(theDisplay.GetWidth()-w);
            int y = rand()%(theDisplay.GetHeight()-h);

            theDisplay.FillRectangle(x,y,x+w,y+h,rand(),rand(),rand());
        }

        theDisplay.FillRectangle(100,100,400,400,255,0,255);

        theDisplay.EndFrame();

    }

// And quit\n";
    return EXIT_SUCCESS;
}
