#include "TinyGLES.h"

#include <iostream>

int main(int argc, char *argv[])
{
// Say hello to the world!
    std::cout << "Hello world, a skeleton app generated by appbuild.\n";

// Display the constants defined by app build. \n";
    std::cout << "Application Version " << APP_VERSION << '\n';
    std::cout << "Build date and time " << APP_BUILD_DATE_TIME << '\n';
    std::cout << "Build date " << APP_BUILD_DATE << '\n';
    std::cout << "Build time " << APP_BUILD_TIME << '\n';

    tinygles::GLES GL(true);

    const uint32_t FTFont = GL.FontLoad("./Blenda Script.otf",40,true);

    int anim = 0;
    while( GL.BeginFrame() )
    {
        anim++;
        GL.Clear(40,20,60);

        GL.FillRoundedRectangle(50,50,GL.GetWidth()-50,GL.GetHeight()-50,100,55,20,155);
        GL.DrawRoundedRectangle(50,50,GL.GetWidth()-50,GL.GetHeight()-50,100,255,255,255);

        GL.FontPrint(80,80,"The fixed built in font for comparison");

        GL.FontPrintf(FTFont,80,200,"Anim: %d",anim);

        GL.EndFrame();

    }

// And quit
    return EXIT_SUCCESS;
}
